name: "🚀 release"

on:
    push:
        branches:
            - master

jobs:
    release:
        name: 🚀 release
        runs-on: ubuntu-latest
        steps:
            - name: 📚 checkout
              uses: actions/checkout@v2.1.1
            - name: 🟢 node
              uses: actions/setup-node@v2.5.1
              with:
                  node-version: "14"
            - name: Build Dist
              run: |
                  npm run build
            - name: 🚀 publish
              run: npm publish --access public
              working-directory: dist
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
